# Setup
title:        Indium
tagline:      A zero transaction cost, low-latency cryptocurrency with safe smart contracts
baseurl:      ""

gitlab-letsencrypt:
  # Gitlab settings:
  personal_access_token: ''             # Gotten from the step above ^^
  gitlab_repo:           'indium/indium.gitlab.io' # Namespaced repository identifier

  # Domain settings:
  email:                 'github@nileshtrivedi.com'     # Let's Encrypt email address
  domain:                'indium.org.in'             # Domain that the cert will be issued for

  # Jekyll settings:
  base_path:  './'               # Where you want the file to go
  pretty_url: true              # Add a "/" on the end of the URL... set to `true` if you use permalink_style: pretty
  filename:   'letsencrypt' # What to call the generated challenge file

  # Delay settings:
  initial_delay: 150 # How long to wait for Gitlab CI to push your changes before it starts checking
  delay_time:     15 # How long to wait between each check once it starts looking for the file

  # Optional settings you probably don't need:
  branch:    'master'            # Defaults to master, but you can use a different branch
  layout:    'null'              # Layout to use for challenge file - defaults to null, but you can change if needed
  scheme:    'http'             # Scheme to use for challenge request; default http
